app:
  telegram-token: ${TELEGRAM_TOKEN}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

api:
  scrapper:
    baseUrl: http://localhost:8080

springdoc:
  swagger-ui:
    path: /swagger-ui
